### ISSUE TITLE
[请求] 可否将lua mod转换为CSharp mod 以增加兼容性

### ISSUE THREAD

**Issue by aylz10** [xyzkljl1/MyBlackMythWukongMods#2]
https://www.nexusmods.com/blackmythwukong/mods/656
和
https://www.nexusmods.com/blackmythwukong/mods/270
这两个mod 与 https://www.nexusmods.com/blackmythwukong/mods/60 大地图mod还是存在兼容性问题，会偶尔造成游戏报错或者闪退
可否写成CSharp的mod以增加兼容性

**Comment by xyzkljl1** [comment]
我没有这个打算，请去找原作者。
